product-review-service.url: ${REVIEW_SERVICE_URL:http://localhost:8081}
spring:
  datasource:
    platform: "h2"
    driverClassName: "org.h2.Driver"
    url: "jdbc:h2:mem:products?useSSL=false&characterEncoding=UTF-8&createDatabaseIfNotExist=true"
    username: "sa"
    password: ""
  jpa:
    database-platform: ""
    hibernate.ddl-auto: "update"
    repositories.enabled: "true"
    defer-datasource-initialization: "true"